version: '3.6'
services:
  db:
    image: wbms/sqld:20240326-1324
    environment:
      - SQLD_ADMIN_LISTEN_ADDR=0.0.0.0:8081
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - ./turso-data:/var/lib/sqld
      - ./docker/turso/ext:/ext
    command: /bin/sqld --enable-namespaces --extensions-path=/ext
